### PR TITLE
Fixed a bug allowing the cursor escape the grid when holding the leff key

### PR DESCRIPTION
**Pull request by mrcyclo**
## Description
Step 1: Enter champion select screen
Step 2: Move cursor to the right
Step 3: Hold the left key

And then, the `currentPos` is less than zero. That make the cursor disapear.

## How Has This Been Tested?
Tested on Windows 11.

### CODE REVIEW

**Comment by sweetriverfish** [comment]
I'll be honest, I was not able to reproduce it ¯\\\_(ツ)_/¯

**Comment by mrcyclo** [comment]
image
Yeah, but I can 😂
Btw, Windows 10 seem like make it much more bugs than Windows 11.

**Comment by sweetriverfish** [comment]
Windows 11 new terminal thingy breaks the application resizing though, it does not properly resize anymore. it only resizes itself properly when I open it via the old conhost.

A while ago I added some piece of code to resize the console according to the current amount of champions in game. With the addition of Smolder, the console now needs to be slightly bigger by 1 row. Windows 11 terminal does not allow this to happen and instead results in some glitchy behavior. Have you not noticed it or did they fix it in some Windows update?

**Comment by sweetriverfish** [comment]
https://github.com/sweetriverfish/LeagueAutoAccept/assets/13397494/a70b75ef-a84c-4446-933d-b40f71efa9b6

**Comment by mrcyclo** [comment]
Yep, I'm also facing a similar issue and still haven't been able to solve it. 😂

**Comment by sweetriverfish** [comment]
You can either change your default terminal to "Windows Console Host" or launch it via conhost.exe ("C:\Windows\System32\conhost.exe" "[Leauge Auto Accept.exe path here]").
image

I'm not sure if there's any other solution to this, looks like an issue with the new Windows terminal.

**Comment by mrcyclo** [comment]
Ah, this is too complicated for end-users, especially since the default startup program for Windows 11 is already Windows Terminal. I have another solution that might be a little better. Hopefully, it runs smoothly.
https://github.com/sweetriverfish/LeagueAutoAccept/pull/39

**Pull request merged**
